vtex-apps/google-tag-manager

CHANGELOG.md
react/index.tsx
react/typings/events.d.ts

Events that had products in it would give the attribute `category` different formats. This PR makes all events related to products use the same semantics of the `category` field.
In some events the field category of a product would come as:
> category: "Apparel & Accessories/Clothing/Tops"
While in others would come as:
> category: "Tops"
This PR makes removes the second way of attributing the category fields.
https://breno--storecomponents.myvtex.com/
Product Impression
Add to Cart
Remove from Cart
Product Detail
Order Placed

Fix category field of product related events

---

.vtexignore
CHANGELOG.md
react/__mocks__/productClick.ts
react/__mocks__/productDetail.ts
react/__mocks__/productImpression.ts
react/__tests__/index.test.tsx
react/index.tsx
react/typings/events.d.ts

The ids sent by this app was inconsistent across navigation. Sometimes we sent the id of the product and some times the id of the SKU. Now, all events are sent using the id of the visible SKU.
Before | After
---|---

Change events to send the id of the visible SKU

---

CHANGELOG.md
react/__mocks__/productClick.ts
react/__mocks__/productDetail.ts
react/__mocks__/productImpression.ts
react/package.json
react/typings/events.d.ts
react/yarn.lock

This app is used as a canonical source for pixel events types. There are new events triggered by our store. This PR update those events types to match the ones that are available.

Fix events typings

---

CHANGELOG.md
manifest.json
react/package.json
react/yarn.lock

Enable configuration by binding
GTM must be configured by binding for some tenants.
https://bindings--powerplanet.myvtex.com/admin/apps/vtex.google-tag-manager@2.3.0/setup/

Enable configuration by binding

---

CHANGELOG.md
react/index.tsx
react/typings/events.d.ts

Updates the `vtex:cart` event handler to handle the `vtex:cartLoaded` event instead.
The `vtex:cart` event is triggered just after the cart page is first rendered, which may not have the orderForm loaded yet, but the `vtex:cartLoaded` is guaranteed to only fire _after_ the orderForm is successfully loaded in the page.
Access [this](https://lucas--checkoutio.myvtex.com/cart/add?sku=289) workspace, and check that the event in `window.dataLayer` contains the item in your cart.

Replace cart with cartLoaded event

---

CHANGELOG.md
react/index.tsx
react/typings/events.d.ts

Related to https://github.com/vtex-apps/store-image/pull/29
Send promotion impressions and clicks
Promotion View: https://developers.google.com/tag-manager/enhanced-ecommerce#promo-impressions
Promotion Click: https://developers.google.com/tag-manager/enhanced-ecommerce#promo-clicks
You can check this workspace:
https://promoview--storecomponents.myvtex.com/
Check the `dataLayer` variable

Add promoView and promotionClick events

---

CHANGELOG.md
react/index.tsx
react/typings/events.d.ts

Improve productClick analytics event.
https://summary--storecomponents.myvtex.com/
1. Open the store
2. Click on a product of the shelf
3. Check the dataLayer for the productClick event
4. Look for the list name info

Add list property to productClick event

---

CHANGELOG.md
react/modules/enhancedEcommerceEvents.ts
react/typings/events.d.ts

Send price property with the correct value when used with `add-to-cart-button`.
https://breno--storecomponents.myvtex.com/
1. Open workspace
2. Add item to cart
3. Check global JS variable `dataLayer`
4. Look for the `addToCart` event
5. Check the `price` property
Depends on 
https://github.com/vtex-apps/add-to-cart-button/pull/66
https://github.com/vtex-apps/minicart/pull/265

Fix price being sent as integer instead of float

---

CHANGELOG.md
pixel/head.html

This PR adds the `originalLocation` variable to the dataLayer during initialization. That makes the campaign info, such as `utm_medium` and `utm_source`, persist during navigation after it's combined with some GTM container configuration.
This PR hopefully solves a problem where the `google/cpc` campaign data would be lost after user navigation.
A bit tricky to go full circle on this, but for this PR purpose, just type `dataLayer` at the console and check if there's an object with an `originalLocation` property inside.
[Workspace](https://icaroprod--storecomponents.myvtex.com)

fix: add originalLocation variable to dataLayer

---

CHANGELOG.md
pixel/head.html

This PR adds the `originalLocation` variable to the dataLayer during initialization. That makes the campaign info, such as `utm_medium` and `utm_source`, persist during navigation after it's combined with some GTM container configuration.
This PR hopefully solves a problem where the `google/cpc` campaign data would be lost after user navigation.
A bit tricky to go full circle on this, but for this PR purpose, just type `dataLayer` at the console and check if there's an object with an `originalLocation` property inside.
[Workspace](https://icaroprod--storecomponents.myvtex.com)
https://github.com/vtex-apps/google-tag-manager/pull/63 This is the fix for the 3.x version of the app. It's exactly the same code and effect.

fix: add originalLocation variable to dataLayer 3.x

---

CHANGELOG.md
react/modules/analytics/index.ts
react/modules/analytics/utils.ts
react/modules/push.ts

This PR fixes `originalLocation` and `originalReferrer` variables not being added to the events sent to the `dataLayer` because the `dataLayer` already had native GTM events in there.
Type `dataLayer` into the console. Only the first event sent by the Google Tag Manager app (usually `pageView`) should have the variables mentioned above.
[Workspace](https://icarogtm--storecomponents.myvtex.com/)

Fixing first push detection

---

CHANGELOG.md
react/modules/enhancedEcommerceEvents.ts

This PR changes the product name on orderPlaced events so that it doesn't include the SKU name.
This PR solves an inconsistency among events. The orderPlaced event should behave as all other events do, and not include the SKU name on the product name. This PR makes the orderPlaced event compliant with this requirement.
[Workspace](https://icarogtm--storecomponents.myvtex.com)

Removing SKU name from product name on orderPlaced events

---

CHANGELOG.md
react/modules/enhancedEcommerceEvents.ts

Historically, users configure one single tag for checkout and orderplaced pages. We want to allow that on version 3.x still.
The checkout uses the `ecommerceV2` variable to get the event data, and it should do the same thing on the orderplaced. They couldn't until today, because there was no variable called `ecommerceV2` on the orderPlaced event. 
On the orderplaced page, type `dataLayer` into the browser console and check if there's an ecommerceV2 property inside the orderPlaced event.
[Workspace](https://icarogtm--storecomponents.myvtex.com/)

Fixing orderPlaced event ecommerceV2 property so it matches the one in the checkout

---

CHANGELOG.md
react/modules/extraEvents.ts

Add the user's encrypted email to the 'userData' data layer.
We need to capture data for Google to increase conversions in Google campaigns. It's about optimized conversions. It is necessary to start receiving the email of the logged in user encrypted in SHA256, that is, an anonymized source data, with this, we will not have problems in terms of LGPD
1. Access Workspace;
2. Log in;
3. In the console, verify that when typing dataLayer, in the 'userData' layer, the 'cryptId' field is displayed, which refers to the user's encrypted email.

feat: add encrypt user mail to userdata Datalayer

---

react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/modules/utils/shouldMergeUAEvents.ts

It sends the [GA4 `select_promotion`](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#select_promotion) event when `vtex:promotionClick` is received. 
https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#select_promotion|
-|
A new test has been added and can be run with `yarn test`.

Sends GA4 `select_promotion`

---

react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/modules/utils.ts

This PR intends to add the `add_to_cart` GA4 event to be sent when `vtex:addToCart` is received.
[`add_to_cart` event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#add_to_cart)|
-|
- In your local environment, inside the `google-tag-manager` app repository, go to the branch `feat/ga4-add-to-cart-event`;
- Login in your preferred account and workspace;
- Link the app;
- Go to the Admin and access the App Store. Look for the Google Tag Manager app and access the `Settings`;
- Check the `Merge Universal Analytics and Google Analytics 4 Events` option;
- Access the store and perform add an item to the cart;
- Check the `dataLayer` object (just type `dataLayer` in the console and press enter). The event data should be in the list.

feat: Adds `add_to_cart` GA4 event

---

react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/typings/events.d.ts

This PR intends to add the `remove_from_cart` GA4 event to be sent when `vtex:removeFromCart` is received.
[`remove_from_cart` event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#remove_from_cart)|
-|
- In your local environment, inside the `google-tag-manager` app repository, go to the branch `feat/ga4-remove-from-cart-event`;
- Login in your preferred account and workspace;
- Link the app;
- Go to the Admin and access the App Store. Look for the Google Tag Manager app and access the `Settings`;
- Check the `Merge Universal Analytics and Google Analytics 4 Events` option;
- Access the store and perform add an item to the cart;
- Check the `dataLayer` object (just type `dataLayer` in the console and press enter). The event data …

feat: Adds `remove_from_cart` GA4 event

---

react/__mocks__/viewPromotion.ts
react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/typings/events.d.ts

Push the GA4's [`view_promotion`](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#view_promotion) event when `vtex:promoView` is triggered.
1. Visit https://filipelimaxga4viewpromo--storecomponents.myvtex.com/.
2. Click the right arrow button to see the next gallery image.
3. Check the `dataLayer` variable in the web console to ensure the `view_promotion` was fired.

Send GA4 view_promotion event

---

.github/workflows/test.yml
react/__mocks__/productClick.ts
react/__mocks__/productDetail.ts
react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/modules/utils.ts
react/typings/events.d.ts

- Add tests to GA4 `select_item`, `view_item`, and `view_item_list` events.
- Remove unused types `CategoryTreeItem` and `CategoryTree`.
- Stop exporting the util function `removeStartAndEndSlash` because it's only used internally.
- Type event payloads for better safety.
Run new and existing tests with `yarn test`.

Add tests to GA4 `select_item`, `view_item` & `view_item_list`

---

CHANGELOG.md
react/__mocks__/addPaymentInfo.ts
react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/modules/utils.ts
react/typings/events.d.ts

This PR intends to add the `add_payment_info` GA4 event to be sent when `vtex:addPaymentInfo` is received.
[`add_payment_info` event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#add_payment_info)|
-|
- In your local environment, inside the `google-tag-manager` app repository, go to the branch `ffeat/ga4-new-add-payment-info-event`;
- Login in your preferred account and workspace;
- Link the app;
- Go to the Admin and access the App Store. Look for the Google Tag Manager app and access the `Settings`;
- Check the `Merge Universal Analytics and Google Analytics 4 Events` option;
- Access the store and perform add an item to the cart;
- Check the `dataLayer` object (just type `dataLayer` in the console and press enter). The event …

Feat/ga4 new add_payment_info event

---

CHANGELOG.md
react/__tests__/index.test.tsx
react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/typings/events.d.ts

This PR intends to add the `share` GA4 event to be sent when `vtex:share` is received.
[`share` event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=en&client_type=gtag#share)|
-|
- In your local environment, inside the `google-tag-manager` app repository, go to the branch `feat/ga4-new-share-event`;
- Login in your preferred account and workspace;
- Link the app;
- Go to the Admin and access the App Store. Look for the Google Tag Manager app and access the `Settings`;
- Check the `Merge Universal Analytics and Google Analytics 4 Events` option;
- Access the store and go to a product page, and perform a share via any social network;
- Check the `dataLayer` object (just type `dataLayer` in the console and press enter). The event data should be in the …

Feat/ GA4 share event

---

react/__mocks__/viewCart.ts
react/modules/gaEvents.ts
react/modules/utils.ts
react/typings/events.d.ts

Correct the object format on the new `view_cart` event triggered on [mincart app](https://github.com/vtex-apps/minicart/blob/feat/add-ga4-viewcart-event/react/Minicart.tsx#L68) 
The event sends different object attributes for categories and price format, so the price was being send as an integer and the categories was not being sended 
* Go to this [branch of minicart app](https://github.com/vtex-apps/minicart/tree/feat/add-ga4-viewcart-event)
* Link minicart app on store
* Switch to [branch with fixes on gtm](https://github.com/vtex-apps/google-tag-manager/tree/fix/ga4-viewcart-event-format) and link on store
* Open the minicart and check on `window.dataLayer` if the item has the correct attributes

Fix/ add categories new format, and price division to `view_cart`

---

react/__tests__/index.test.tsx

The event should have been called `add_to_wishlist`, not `view_item`.

Fix minor error in the `add_to_wishlist` test

---

react/modules/enhancedEcommerceEvents.ts
react/modules/gaEvents.ts
react/typings/events.d.ts

I noticed the `CartData` type inside the interface `PixelMessage` wasn't defined anywhere in the project and decided to remove it.
Because it was unresolved, it took the type of `any`. This caused our event types to lose effectiveness as `any` was too wide. It surfaced as many as 31 type errors that we weren't handling! This PR addresses these errors.
Originally added [here](https://github.com/vtex-apps/google-tag-manager/pull/38/files#diff-791619406f30fb7292cdecb798d2a840d54a926399fdcd740a7706dbe852c9a6), it was later [renamed](https://github.com/vtex-apps/google-tag-manager/pull/40/files#diff-791619406f30fb7292cdecb798d2a840d54a926399fdcd740a7706dbe852c9a6) to `CartLoadedData` but `CartData` [remained](https://github.com/vtex-apps/google-tag-manager/blob/f785e969c4b947a8c699598c46bdefde3 …

Fix many hidden type errors

---

CHANGELOG.md
react/modules/utils.ts

Fix purchase GA4 event
The purchase event has a wrong format to categories hierarchy. Actually there is just one level to item_category and correct is to have all category tree splitted by level, like item_category, item_category2, item_category3... 
Generate a purchase event and check the format of item_category

Fixing category hierarchy to purchase event
